version: "3.2"

services:
  nos:
    image: nos
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nos
#    restart: "unless-stopped"
    volumes:
      - ./gamedata/:/home/steam/nos/
      - ./Game.ini:/home/steam/Game.ini 
      - ./backup/:/home/steam/backup/:rw
      - ./start.sh:/etc/entrypoint.sh
      - ./backup.sh:/home/steam/backup.sh
      - ./crontab.txt:/home/steam/crontab.txt
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=911
      - PGID=911
      - STEAMAPPID=2329680
      - STEAMAPPDIR=/home/steam/nos
      - STEAMCMDDIR=/home/steam/steamcmd
      - NOS_ARGS=-USEALLAVAILABLECORES -high -preload -log -server
    ports:
      - 7767:7767/udp
      - 7768:7768/udp
      - 27014:27014/udp
